### ISSUE TITLE
Front-end ( Pleno | Sênior ) - Fernanda Maia

### ISSUE THREAD

**Issue by fernandamaiait** [fliperdev/mobile-flutter-test#12]
Olá, Aline!

Eu estou deixando meu código aqui só pra mostrar pra vocês que eu tentei! =)

Eu nunca trabalhei com graphql e não fui capaz de aprender em um fim de semana.
Então eu deixo pra vocês o código de até onde eu cheguei.
Eu ia desenvolver a parte de gerenciamento de estado logo depois de pegar os dados, mas como não consegui, não desenvolvi também.
Não coloquei as fontes que o designer colocou no XD porque ele não achei ela no repositório de vocês.
Obrigada pela oportunidade, quem sabe no futuro eu aprendo a mexer com graphql e me candidato novamente?! =)
Segue o link para o meu repositório:
https://github.com/fernandamaiait/testefliper

 
Muito grata,

Fernanda

**Comment by amandamussio** [comment]
@fernandamaiait  Olá Fernanda, sou a Amanda líder do time de mobile aqui no Fliper. Fico muito feliz quando vejo outras mulheres engajadas na área de tecnologia.
Obrigada por ter se disposto a fazer nosso teste e entregar o seu melhor. Peço desculpas na demora da resposta,
pois não tínhamos visto seu comentário aqui nesta issue.
No momento estamos em busca de uma pessoa desenvolvedora com mais senioridade nas tecnologias que já usamos, mas estou guardando seu teste e seu contato, quem sabe
em breve podemos voltar a conversar não é mesmo?
Ótimo 2021, sucesso e muito aprendizado para este ano.

**Comment by fernandamaiait** [comment]
Oi, Amanda!
Obrigada por seu retorno! =)

Até mais!

Fernanda
