### ISSUE TITLE
Front-end ( Pleno | Sênior ) - Glaidson Montanhini

### ISSUE THREAD

**Issue by GlaidsonRM** [fliperdev/mobile-flutter-test#13]
Boa tarde, Amanda.

Criei o aplicativo conforme descrito nos requisitos.
O projeto foi criado em flutter, usei o gerenciamento de estado do GetX, e implementei mais algumas novidades no aplicativo.
O aplicativo tem a opção de ser alterado o tema, também criei um processo que busca atualizações de tempo em tempo que também pode ser definida pelo usuário.
Grato pela oportunidade, foi uma parte do meu trabalho que amo desenvolver com flutter.
Duvidas estou a disposição, segue link do meu repositório.
https://github.com/GlaidsonRM/fliper_glaidson

- [x] O projeto deverá ser feito em flutter.
- [x] Esperamos alguma alternativa de gerência de estado.
- [x] Sinta-se a vontade para ousar no projeto.

**Comment by amandamussio** [comment]
Olá @GlaidsonRM boa tarde! Sou a Amanda responsável pela área de mobile aqui na Fliper!
Obrigada por entregar o teste e por deixar um mensagem sobre suas intenções aqui pra gente!
Vamos avaliar e a Aline entrará em contato com você nos próximos dias, tudo bem?

Um ótimo final de semana!

**Comment by GlaidsonRM** [comment]
Olá @amandamussio eu que agradeço pela oportunidade, qualquer dúvida estou a disposição, perfeito, aguardo o retorno.
Um ótimo final de semana pra você também.
