### ISSUE TITLE
Front-end ( Pleno | Sênior ) - Filipe Morelli

### ISSUE THREAD

**Issue by filipemorelli** [fliperdev/mobile-flutter-test#15]
Boa noite, @amandamussio.

O projeto foi criado em Flutter. O gerenciamento de estado usado foi MobX com modular. Como foi livre a escolha resolvi usar esse gerenciamento de estado por ser mais comum na comunidade principalmente por causa do Fluterando. Adicionei algumas recursos extras como internacionalização dos textos e null safety.

Link do repositório: https://github.com/filipemorelli/fliper-sample

**OBS:** Senti falta da font para usar no projeto. Até achei na internet porém seria de maneira ilícita então preferi não utilizar.

Qualquer duvida pode entrar em contato terei prazer em esclarecer.

**Comment by amandamussio** [comment]
Olá @filipemorelli boa tarde! Sou a Amanda responsável pela área de mobile aqui na Fliper!
Obrigada por entregar o teste e por deixar um mensagem sobre a linha de raciocínio e decisões!
Vamos avaliar e a Aline entrará em contato com você nos próximos dias, tudo bem?

Um ótimo feriado!
