### ISSUE TITLE
Front-end ( Pleno | Sênior ) - Eric Omine

### ISSUE THREAD

**Issue by ericomine** [fliperdev/mobile-flutter-test#16]
Disponibilizei meu projeto para avaliação [aqui](https://github.com/ericomine/flipme_app/). Coloquei observações que achei pertinentes no README deste repositório.
Obrigado!

**Comment by amandamussio** [comment]
Olá @ericomine boa tarde! Sou a Amanda responsável pela área de mobile aqui na Fliper! 
Obrigada por entregar o teste!
Vamos avaliar e a Aline entrará em contato com você nos próximos dias, tudo bem?

Um ótimo feriado!

**Comment by ericomine** [comment]
Obrigado pelo aviso.
Ótimo feriado para você também!

**Comment by ericomine** [comment]
Oi, @amandamussio. Ainda não recebi nenhum retorno, você pode cobrar o time do RH aí? Obrigado.
