### ISSUE TITLE
Front-end ( Pleno | Sênior ) - Vitor Yugulis

### ISSUE THREAD

**Issue by vitoryugulis** [fliperdev/mobile-flutter-test#17]
Obrigado pela oportunidade.

[Link do teste.](https://github.com/vitoryugulis/graphql-flutter)

**Comment by amandamussio** [comment]
Olá @vitoryugulis boa tarde! Sou a Amanda responsável pela área de mobile aqui na Fliper!
Obrigada por entregar o teste!
Vamos avaliar e a Aline entrará em contato com você nos próximos dias, tudo bem?

Um ótimo feriado!
